# Generated by Django 5.0.6 on 2024-06-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpreference',
            table='user_preference',
        ),
    ]
